import Head from "next/head";
import TrueContent from "@/components/TrueContent/TrueContent";
import Toolbar from "@/components/MudToolbar/MudToolBar";
import ExamplePage from "@/components/PatternsPages/Example/ExamplePattern";
import CardPatternDefault from "@/components/PatternsComponents/CardPattern/CardDefault";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ExamplePage />
    </>
  );
}
