import Head from "next/head";
import TrueContent from "@/components/MudContent/MudContent";
import Toolbar from "@/components/MudToolbar/MudToolBar";
// import ExamplePage from "@/components/Patterns/Example/ExamplePattern";
import PageTemplate from "@/components/Patterns/Pages/PageTemplate";
import CardPatternDefault from "@/components/PatternsComponents/CardPattern/CardDefault";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <ExamplePage /> */}
      <PageTemplate />
    </>
  );
}
